// <auto-generated />
using CRUDANGGOTA.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace CRUDANGGOTA.Migrations
{
    [DbContext(typeof(AnggotaContext))]
    [Migration("20190705050112_Intial Create")]
    partial class IntialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.4-servicing-10062")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("CRUDANGGOTA.Models.Anggota", b =>
                {
                    b.Property<int>("AnggotaID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Jabatan")
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Nama")
                        .IsRequired()
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("Nim")
                        .HasColumnType("varchar(100)");

                    b.HasKey("AnggotaID");

                    b.ToTable("Anggotas");
                });
#pragma warning restore 612, 618
        }
    }
}
